cask "font-iosevka-term-ss04-nerd-font" do
  version "34.6.3"
  sha256 "10e202c7258d2d532e51d71c5e11ee58b44e127eb596d0078bde6f49dafdd5df"

  url "https://github.com/caelumix/Custom-Iosevka-Nerd-Font/releases/download/v#{version}/IosevkaTermSS04-nerd-font-#{version}.zip"
  name "Iosevka Term SS04 Nerd Font"
  homepage "https://github.com/caelumix/Custom-Iosevka-Nerd-Font"

  font "IosevkaTermSS04NerdFontMono-Bold.ttf"
  font "IosevkaTermSS04NerdFontMono-BoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-BoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Extended.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedBold.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedBoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedBoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraBold.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraBoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraBoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraLight.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraLightItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedExtraLightOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedHeavy.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedHeavyItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedHeavyOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedLight.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedLightItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedLightOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedMedium.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedMediumItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedMediumOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedSemiBold.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedSemiBoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedSemiBoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedThin.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedThinItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtendedThinOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraBold.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraBoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraBoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraLight.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraLightItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ExtraLightOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Heavy.ttf"
  font "IosevkaTermSS04NerdFontMono-HeavyItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-HeavyOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Italic.ttf"
  font "IosevkaTermSS04NerdFontMono-Light.ttf"
  font "IosevkaTermSS04NerdFontMono-LightItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-LightOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Medium.ttf"
  font "IosevkaTermSS04NerdFontMono-MediumItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-MediumOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Oblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Regular.ttf"
  font "IosevkaTermSS04NerdFontMono-SemiBold.ttf"
  font "IosevkaTermSS04NerdFontMono-SemiBoldItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-SemiBoldOblique.ttf"
  font "IosevkaTermSS04NerdFontMono-Thin.ttf"
  font "IosevkaTermSS04NerdFontMono-ThinItalic.ttf"
  font "IosevkaTermSS04NerdFontMono-ThinOblique.ttf"

end
